version: "3.8"

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=dmydatabase
      - REDIS_URL=redis://redis:6379/0
      - TZ=America/Phoenix

  celery:
    build: .
    command: celery -A API.celery worker --pool=solo -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - TZ=America/Phoenix

  celerybeat:
    build: .
    command: celery -A API beat --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0\
      - TZ=America/Phoenix

volumes:
  mysql_data:
